### ISSUE TITLE
Cupy.ElementwiseKernel issues

### ISSUE THREAD

**Issue by jsbtic** [JorgeGtz/SolidTextureNets#2]
Hi,
 can I ask with which version of Cuda have you run the program with? The `train_slice.py` runs fine (with cupy `v8.3.0` & cuda 10.1, `V10.1.243`), but the `sample_on_demand.py` crashes
 
 ```bash 
 $ python3 sample_on_demand.py 
 0,0,0
Traceback (most recent call last):
  File "/home/myuser/anaconda3/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 554, in compile
    nvrtc.compileProgram(self.ptr, options)
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 108, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 120, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 58, in cupy_backends.cuda.libs.nvrtc.check_status
cupy_backends.cuda.libs.nvrtc.NVRTCError: NVRTC_ERROR_COMPILATION (6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sample_on_demand.py", line 291, in <module>
    z_0 = torch.from_numpy(sample_noise(d1_1-4,d1_2+4,d2_1-4,d2_2+4,d3_1-4,d3_2+4,3,0)).unsqueeze(0)
  File "sample_on_demand.py", line 234, in sample_noise
    hash_seed = wang_hash64(seed)
  File "cupy/core/_kernel.pyx", line 821, in cupy.core._kernel.ElementwiseKernel.__call__
  File "cupy/core/_kernel.pyx", line 846, in cupy.core._kernel.ElementwiseKernel._get_elementwise_kernel
  File "cupy/_util.pyx", line 59, in cupy._util.memoize.decorator.ret
  File "cupy/core/_kernel.pyx", line 639, in cupy.core._kernel._get_elementwise_kernel
  File "cupy/core/_kernel.pyx", line 37, in cupy.core._kernel._get_simple_elementwise_kernel
  File "cupy/core/_kernel.pyx", line 60, in cupy.core._kernel._get_simple_elementwise_kernel
  File "cupy/core/core.pyx", line 1882, in cupy.core.core.compile_with_cache
  File "/home/myuser/anaconda3/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 373, in compile_with_cache
    return _compile_with_cache_cuda(
  File "/home/myuser/anaconda3/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 440, in _compile_with_cache_cuda
    ptx, mapping = compile_using_nvrtc(
  File "/home/myuser/anaconda3/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 211, in compile_using_nvrtc
    return _compile(source, options, cu_path,
  File "/home/myuser/anaconda3/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 195, in _compile
    ptx, mapping = prog.compile(options, log_stream)
  File "/home/myuser/anaconda3/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 565, in compile
    raise CompileException(log, self.src, self.name, options,
cupy.cuda.compiler.CompileException: /tmp/tmptretg_c7/aeb323ad9e87bda25550467fb3f68cb0_2.cubin.cu(13): error: expression must be a modifiable lvalue

/tmp/tmptretg_c7/aeb323ad9e87bda25550467fb3f68cb0_2.cubin.cu(13): error: expression must be a modifiable lvalue

/tmp/tmptretg_c7/aeb323ad9e87bda25550467fb3f68cb0_2.cubin.cu(13): error: expression must be a modifiable lvalue

/tmp/tmptretg_c7/aeb323ad9e87bda25550467fb3f68cb0_2.cubin.cu(13): error: expression must be a modifiable lvalue

/tmp/tmptretg_c7/aeb323ad9e87bda25550467fb3f68cb0_2.cubin.cu(13): error: expression must be a modifiable lvalue

/tmp/tmptretg_c7/aeb323ad9e87bda25550467fb3f68cb0_2.cubin.cu(13): error: expression must be a modifiable lvalue

6 errors detected in the compilation of "/tmp/tmptretg_c7/aeb323ad9e87bda25550467fb3f68cb0_2.cubin.cu".
```
As far as I can tell, cupy takes issue with the custom `wang_hash` -kernel
```python
wang_hash64 = cp.ElementwiseKernel(
    'uint64 key',
    'uint64 out_key',
    'key = (~key) + (key << 21); \
    key = key ^ (key >> 24); \
    key = (key + (key << 3)) + (key << 8);\
    key = key ^ (key >> 14); \
    key = (key + (key << 2)) + (key << 4); \
    key = key ^ (key >> 28); \
    out_key = key + (key << 31);',
    'wang_hash64')
```
or to be more precise, cupy 8 doesn't like the modification of the input variable (`key`). 

Here's a MWE
```python
import cupy as cp

hash64 = cp.ElementwiseKernel(
    'uint64 key',
    'uint64 out_key',
    'key = 1*key; \
    out_key = key + (key << 31);',
    'wang_hash64')

a = (cp.random.randint(1,10)).astype(cp.uint64)

print(hash64(a))
```
Unfortunately I don't know enough about cupy to understand whether such issues are due to removed support for these types of custom kernels in current cupy version or whether I'm just doing something silly =S...

Does anyone else have the same issue?

My best

**Comment by JorgeGtz** [comment]
Hi,
Unfortunately I did not think on keeping a record of the versions I was using and I don't have that computer anymore.
I believe it was CUDA 8... I will try and see if I can find a solution.
In the meantime, if you want to generate a fixed sized sample you could feed the generator with random inputs from pytorch.

**Comment by jsbtic** [comment]
Hi,
   thank you for your reply. Affirmative, the following (crude) adaptation seems to do the job (>= Cuda 9.1)

-----------------   
 ```python
   wang_hash64 = cp.ElementwiseKernel(
    'uint64 key',
    'uint64 out_key',
    'out_key = (~key) + (key << 21); \
    out_key = out_key ^ (out_key >> 24); \
    out_key = (out_key + (out_key << 3)) + (out_key << 8);\
    out_key = out_key ^ (out_key >> 14); \
    out_key = (out_key + (out_key << 2)) + (out_key << 4); \
    out_key = out_key ^ (out_key >> 28); \
    out_key = out_key + (out_key << 31);',
    'wang_hash64')
```
   ----------------
```python
xorshift64star = cp.ElementwiseKernel(
    'uint64 x',
    'uint64 r',
    'r = x^x >> 12; \
    r ^= r << 25; \
    r ^= r >> 27; \
    r  = r * 0x2545F4914F6CDD1D;',
    'xorshift64star')
```
and the following to `def sample_noise(x1,x2,y1,y2,z1,z2,n_ch,scale):`
```
    # noise = xorshift64star(hash_seed)
    noise = ((1.0*xorshift64star(hash_seed)) / (18446744073709551615)).astype(cp.float32)
```
